### ISSUE TITLE
Custom environment 

### ISSUE THREAD

**Issue by Dahlaan** [DIT113-V22/group-15#30]
- As a marketing executive, I want the environment in the emulator to represent a real store so that potential customers can get a better understanding of how the assistant will work. 

**Acceptance criteria** 
- The environment should represent a real world store. 

**WikiLink** :  https://github.com/DIT113-V22/group-15/wiki/Store-Requirements

**Comment by LabibaKararEshaba** [comment]
This issue is half-done and thus not implemented.
